version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  app_ao:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: adrianolczak_prod
    restart: always
    networks:
      - default
      - nginx_network
    env_file:
      - .env
    volumes:
      - static:/app/adrianolczak/static
      - media:/app/adrianolczak/media
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy

volumes:
  static:
  media:
  database:

networks:
  nginx_network:
    external: true