# Generated by Django 4.1.6 on 2023-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_bio_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_link',
            field=models.URLField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, max_length=65),
        ),
    ]
