# Generated by Django 4.1.6 on 2023-02-24 21:05

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/user_default.png', upload_to=account.models.user_directory_path),
        ),
    ]
