# Generated by Django 4.1.6 on 2023-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
