# Generated by Django 4.1.6 on 2023-02-12 17:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=blog.models.post_directory_path),
        ),
    ]
