name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: 
      name: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute deployment script on server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        DEPLOY_SCRIPT: ${{ secrets.DEPLOY_SCRIPT }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

        ssh -o StrictHostKeyChecking=no -i private_key -p $SSH_PORT $SSH_USERNAME@$SERVER_IP "$DEPLOY_SCRIPT"

        rm -f private_key
